# Generated by Django 2.2.6 on 2020-09-18 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicationuser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_satus', models.CharField(blank=True, choices=[('provider', 'PROVIDER'), ('seeker', 'SEEKER')], max_length=10, null=True)),
                ('service_catogory', models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('electrician', 'Electrician'), ('painting', 'Painting'), ('furniture', 'Furniture Assembly')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phonenumber', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='pic/')),
                ('rating', models.IntegerField(default=0)),
                ('rated_user_count', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobId', models.IntegerField(blank=True, null=True)),
                ('genaratedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('labour_cost', models.IntegerField(default=0)),
                ('resource_cost', models.IntegerField(default=0)),
                ('ammount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('pending', 'PENDING'), ('done', 'DONE')], default='pending', max_length=10)),
                ('bill_pic', models.ImageField(blank=True, null=True, upload_to='bill/')),
            ],
            options={
                'ordering': ['payment_id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobName', models.CharField(blank=True, max_length=40, null=True)),
                ('job_title', models.CharField(choices=[('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('electrician', 'Electrician'), ('painting', 'Painting'), ('furniture', 'Furniture Assembly')], max_length=30, null=True)),
                ('job_discription', models.TextField(blank=True, null=True)),
                ('assignDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_status', models.CharField(choices=[('request', 'REQUEST'), ('accept', 'ACCEPT'), ('done', 'DONE'), ('reject', 'REJECT')], default='request', max_length=10)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_provider', to='core.Applicationuser')),
                ('seeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker', to='core.Applicationuser')),
            ],
            options={
                'ordering': ['job_id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=750)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Job')),
            ],
            options={
                'ordering': ['cid', 'rating'],
            },
        ),
    ]
