# Generated by Django 2.1.7 on 2020-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200302_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='labour_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='resource_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('request', 'REQUEST'), ('accept', 'ACCEPT'), ('done', 'DONE')], default='request', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
