# Generated by Django 2.1.7 on 2020-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200323_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='status',
            new_name='job_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='bill_pic',
            field=models.ImageField(blank=True, null=True, upload_to='bill/'),
        ),
    ]
