# Generated by Django 2.1.7 on 2020-03-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200324_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='labour_cost',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
