# Generated by Django 2.1.7 on 2020-03-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200324_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Job'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='labour_cost',
            field=models.IntegerField(default=0),
        ),
    ]
